### ISSUE TITLE
Issue with this working on mobile devices

### ISSUE THREAD

**Issue by Kornstalx** [EmilStenstrom/mybgg#10] opened 2018-05-21 05:12 UTC
Having trouble narrowing this down but I'm going to assume it has to do with Algolia or the stylesheet and device screen resolution, but I can't get my custom site to work on mobile. All I see is the Algolia placeholder in chrome (and firefox) on both my phones. The exact same thing happens in Bluestacks, as well. 

It works fine on my old 1920x1080 Samsung tablet. Everything is on the same network when testing.

**Comment by EmilStenstrom** [comment] 2018-05-21 06:54
Unfortunately, I don't have an Android phone to reproduce this on. I've tried Chrome on my PC, with a smaller screensize set, but your site seems to work well there. 

**Since this is likely a javascript error**, is it possible to enable some kind of developer mode in Chrome or Firefox on your phone, and post the error message you get here?

**Comment by Kornstalx** [comment] 2018-05-21 13:19
There isn't an error it just simply doesn't display anything. I tried this on a friend's phone and it works fine, so it must just be an issue with my phones. However it's so odd that it's broken the same way in Bluestacks (an android emulator) as well.

**Comment by EmilStenstrom** [comment] 2018-05-21 13:28
If it was somehow possible to start the browser in a debug mode, I'm sure the error would be there. Problem is, the error is in the web console, and that's not visible by default... If the site is empty, it's because the Algolia javascript didn't load, and that can only happen if there's a javascript error. 

I tried installing Bluestacks, and it did hang during the setup step. I'll see if I can get a hold of an Android phone and reproduce this, otherwise it's too hard to debug unfortunately.

**Comment by danishbuddha** [comment] 2018-06-05 08:36
i i got this on my chromebook with and javascript error {"message":"indexName is not valid","status":400}

**Comment by EmilStenstrom** [comment] 2018-06-05 08:40
@danishbuddha That looks like the name of your Algolia index is incorrectly set. Could you doublecheck that it's correct?

**Comment by EmilStenstrom** [comment] 2018-07-06 13:03
Hi again,

I found some minor errors in my javascript code, so I've run it through a validator to make sure I'm strictly using correct code. Would you mind trying again with the latest version of mybgg?

**Comment by Kornstalx** [comment] 2018-07-06 17:38
Hey I'm not sure who you were replying to, but just FYI it's still not working in Bluestacks. This is probably just an android <5.1 issue.

**Comment by EmilStenstrom** [comment] 2018-07-22 13:59
@Kornstalx I now have an account in BrowserStack which lets my test the site on real mobile devices. It seems to work on Galaxy S5 using Android 4.4. Which specific device are you using? I'm testing towards https://games.emilstenstrom.se, which specifik URL are you testing against?

**Comment by EmilStenstrom** [comment] 2018-10-14 10:51
I'm closing this, not because it's solved, but because I don't have enough info to proceed.

**Closed by EmilStenstrom** 2018-10-14 10:51 UTC
